databases:
  - name: seif
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: volt
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & python3 -m zelz
    region: frankfurt
    envVars:
      - key: ALIVE_NAME
        sync: false
      - key: APP_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: ENV 
        value: ANYTHING
      - key: STRING_SESSION
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.9
      - key: TZ
        value: Asia/Baghdad 
      - key: DATABASE_URL
        fromDatabase:
          name: seif
          property: connectionString   
    autoDeploy: false
